Feature/34 home page
VirtuozPlay/VirtuozPlay pull request #36
Opened 2023-07-03 09:50 UTC by MetalBrackets

close #34

2023-07-03 15:41 UTC, MisterPeModder requested changes

2023-07-03 15:41 UTC, MisterPeModder commented on assets/assets/main.css
> +        border-radius: 100px;
You should *not* use global CSS, only Tailwind, and very rarely scoped CSS *inside* the components themselves.

2023-07-03 15:41 UTC, MisterPeModder commented on assets/components/IconApp.vue
> +const props = defineProps({
Please use the typed variant of defineProps (doc at https://vuejs.org/guide/typescript/composition-api.html#typing-component-props)

2023-07-03 15:41 UTC, MisterPeModder commented on assets/components/IconApp.vue
> +    border-radius: 4px;
Please use multiples of 0.25em for sizes (and their corresponding classes like p-1, p-2, m-4, etc...)

2023-07-03 15:41 UTC, MisterPeModder commented on assets/components/NavBar.vue
> +});
This function call is redundant, you safely remove it.

2023-07-03 15:41 UTC, MisterPeModder commented on tsconfig.vitest.json
> +    "allowJs": true,
Do not use this, we are exclusively using TypeScript.

2023-07-04 08:11 UTC, angemarchand approved these changes

2023-07-10 09:15 UTC, merged