Feature/14 sound acquisition
VirtuozPlay/VirtuozPlay pull request #37
Opened 2023-07-03 13:44 UTC by MelvinCou

Closes #14

2023-07-03 15:11 UTC, MisterPeModder requested changes

2023-07-03 15:11 UTC, MisterPeModder commented on assets/utilities/sound/notes.ts
> +export const notes: { note: string; frequency: number; power: number | undefined }[] = [
Maybe defining a type here would make to code easier to use down the line?
```typescript
export interface Note {
    note: string;
    frequency: number;
    power?: number;
}

// using it
export const notes: Note[] = [
    // ...
];
```

2023-07-03 15:11 UTC, MisterPeModder commented on assets/utilities/sound/microphone.ts
> + */
:eyes:

2023-07-04 07:53 UTC, MisterPeModder requested changes

2023-07-04 07:53 UTC, MisterPeModder commented on assets/utilities/sound/microphone.ts
> +const getTones = (EnableCanvas: boolean = false) => {
Why is `EnableCanvas` capitalized?

2023-07-04 07:53 UTC, MisterPeModder commented on assets/utilities/sound/microphone.ts
> +const InitMicrophone = (EnableCanvas: boolean = false) => {
Why is `EnableCanvas` capitalized?

2023-07-11 08:53 UTC, MisterPeModder requested changes
:clap: :clap:

2023-07-11 08:53 UTC, MisterPeModder commented on front/components/HomeLink.vue
> +    <div class="relative" @mouseover="emit('select')" @focusin="emit('select')">
Why the change?

2023-07-11 08:53 UTC, MisterPeModder commented on front/utilities/sound/canvas.ts
> +export default showCanvas;
This could have been a Vue component

2023-07-11 08:53 UTC, MisterPeModder commented on front/utilities/sound/microphone.ts
> +const getTones = (enableCanvas = false, DecibelMin: number) => {
`DecibelMin` should be written as `decibelMin`.

2023-07-11 08:53 UTC, MisterPeModder commented on front/utilities/sound/microphone.ts
> +        requestAnimationFrame(() => getTones(enableCanvas, DecibelMin));
This spins indefinitely, completely ignoring the browser's animation framerate.

2023-07-11 08:53 UTC, MisterPeModder commented on front/views/TestMicView.vue
> +import PlayMic from '@/components/sound/PlayMic.vue';
This file is redundant, please remove it.

2023-07-11 16:42 UTC, MisterPeModder requested changes
It works! Juste a tiny comment to fix though

2023-07-11 16:42 UTC, MisterPeModder commented on front/utilities/sound/microphone.ts
> + * @param decibelMin    Minimum binary value of decibel to track (between 0 and 255)
Those parameters don't exist anymore.

2023-07-11 18:20 UTC, MisterPeModder approved these changes

2023-07-11 20:27 UTC, angemarchand approved these changes

2023-07-11 20:27 UTC, merged