Send detected notes to back
VirtuozPlay/VirtuozPlay pull request #64
Opened 2023-07-25 12:37 UTC by MelvinCou

1. Go to /checkup
2. Click "start"
3. Do sound
4. Click stop (TODO: error in console: db)
5. Copy ID in terminal
6. Query in graphql sandbox by perf ID

Closes #62

2023-07-25 13:48 UTC, MisterPeModder approved these changes

2023-07-25 13:48 UTC, MisterPeModder commented on front/utilities/sound/microphone.ts
> +                ID: 'CXKu0YxHzIgBrwtXS42Ld',
Il faudra créer (et éventuellement finir) une performance avec
```graphql
mutation StartPerformance($songId: ID!) {
    startPerformance(songId: $songId) {
        id
    }
}
```

2023-07-25 13:49 UTC, MisterPeModder requested changes
My bad.

2023-07-31 15:35 UTC, MisterPeModder approved these changes

2023-07-31 15:35 UTC, MetalBrackets approved these changes
ok

2023-07-31 15:36 UTC, merged