Disable sending performances to database
VirtuozPlay/VirtuozPlay pull request #73
Opened 2023-08-29 08:11 UTC by MelvinCou

Closes #72

2023-08-29 08:55 UTC, MisterPeModder requested changes
Pour fixer les erreurs en DB, il serait peut être mieux d'ajouter un formulaire HTML pour mettre l'id de la chanson, cela permettrai que ca fonctionne dans nos bases de données respectives sans avoir à changer manuellement l'ID dans le code.

2023-08-29 08:55 UTC, MisterPeModder commented on models/repository/performances.go
> +	// if err := models.WrapValidation(r.db.ValidateAndSave(perf)); err != nil {
Je suis pas fan de désactiver les fonctionnalités du back pour pouvoir cacher les erreurs du front

2023-09-04 07:34 UTC, MisterPeModder approved these changes

2023-09-04 07:41 UTC, MetalBrackets approved these changes
yes

2023-09-04 07:43 UTC, merged